
29/08/2019 12:30:25
 | WARNING | auth.py | Falha na autenticação

29/08/2019 12:30:25
 | INFO | _internal.py | 127.0.0.1 - - [29/Aug/2019 12:30:25] "POST /sign-in HTTP/1.1" 200 -
